### ISSUE TITLE
Question:  readonly attributes with no modifications at all being allowed

### ISSUE THREAD

**Issue by Dashman99** [diosney/node-sequelize-noupdate-attributes#1]
Is it true that if I want to create a truly read-only Sequelize model, I need to use this npm package and set EVERY field attribute to `noUpdate: {readOnly: true}`  ???

**Comment by diosney** [comment]
Well, yes, this is one way to accomplish that, I don't know if there are others, which they might.

The only caveat is when it is a new record, as the README says:

>which effectively disables any modification on the content attribute, no matter if the previous value was null or not, though exception is when the record is new.

since, as you can see, in the code it reads:

```js
 if (instance.isNewRecord) {
      return;
    }
```

but I think this is the desired in most situations (tell me if not to add an options to disable it, if you needed).

Also, if you want to set the entire model fields to readonly right now is the only way since Model noupdate is not currently supported, but could be a good addition, so tell me to add it.
